// Shared product data — used by products.tsx and the slug page
export const PRODUCTS = [
  {
    id: 1,
    name: "Chronos Elite",
    slug: "chronos-elite",
    category: "Smart Watches",
    price: 199.99,
    oldPrice: 249.0,
    rating: 5,
    stock: 12,
    badge: "Trending",
    description:
      "The Chronos Elite is our flagship smartwatch, combining cutting-edge technology with a sleek design. Featuring a stunning AMOLED display, 7-day battery life, heart rate monitoring, GPS tracking, and water resistance up to 50 meters. Perfect for professionals and fitness enthusiasts alike.",
    features: [
      "7-day battery life",
      "Heart rate & SpO2 monitoring",
      "Built-in GPS",
      "Water resistant 50m",
      "AMOLED display",
      "Sleep tracking",
    ],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "James M.",
        rating: 5,
        comment:
          "Absolutely love this watch. Best purchase I've made this year!",
      },
      {
        name: "Sarah K.",
        rating: 5,
        comment:
          "Sleek design and the battery lasts forever. Highly recommend.",
      },
      {
        name: "David O.",
        rating: 4,
        comment: "Great watch overall. GPS is very accurate.",
      },
    ],
  },
  {
    id: 2,
    name: "Nova Sport Pro",
    slug: "nova-sport-pro",
    category: "Smart Watches",
    price: 149.99,
    oldPrice: 189.0,
    rating: 4,
    stock: 8,
    badge: "Trending",
    description:
      "Built for athletes, the Nova Sport Pro tracks every move with precision. Features advanced workout detection, VO2 max estimation, and real-time coaching. With a rugged design and 5-day battery, it's your perfect training partner.",
    features: [
      "5-day battery life",
      "Advanced workout detection",
      "VO2 max estimation",
      "Real-time coaching",
      "Rugged design",
      "Water resistant 30m",
    ],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Kevin T.",
        rating: 4,
        comment: "Great sports watch. The workout detection is spot on.",
      },
      {
        name: "Lisa N.",
        rating: 5,
        comment: "Perfect for my marathon training!",
      },
      {
        name: "Mark A.",
        rating: 4,
        comment: "Good value for money. Battery could be better.",
      },
    ],
  },
  {
    id: 3,
    name: "Apex Fitness Band",
    slug: "apex-fitness-band",
    category: "Smart Watches",
    price: 89.99,
    oldPrice: 120.0,
    rating: 5,
    stock: 15,
    badge: "Trending",
    description:
      "The Apex Fitness Band is the ultimate companion for your health journey. Lightweight and comfortable, it tracks steps, calories, sleep, and stress levels throughout the day. Syncs seamlessly with your smartphone.",
    features: [
      "Step & calorie tracking",
      "Sleep monitoring",
      "Stress level detection",
      "Smartphone notifications",
      "10-day battery life",
      "Lightweight design",
    ],
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Alice W.",
        rating: 5,
        comment: "Love how lightweight it is. Wear it 24/7!",
      },
      {
        name: "Tom B.",
        rating: 5,
        comment: "Sleep tracking is incredibly accurate.",
      },
      {
        name: "Grace L.",
        rating: 4,
        comment: "Great budget option for fitness tracking.",
      },
    ],
  },
  {
    id: 4,
    name: "Luxe Gold Watch",
    slug: "luxe-gold-watch",
    category: "Smart Watches",
    price: 299.99,
    oldPrice: 369.0,
    rating: 4,
    stock: 10,
    badge: "Trending",
    description:
      "The Luxe Gold Watch blends luxury aesthetics with smart technology. Featuring a premium stainless steel case, sapphire crystal display, and gold-tone finish. Smart enough for the boardroom, stylish enough for a gala.",
    features: [
      "Stainless steel case",
      "Sapphire crystal display",
      "Gold-tone finish",
      "NFC payments",
      "3-day battery life",
      "Water resistant 30m",
    ],
    images: [
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Robert K.",
        rating: 4,
        comment: "Looks stunning. Gets compliments everywhere I go.",
      },
      {
        name: "Emma P.",
        rating: 5,
        comment: "Perfect blend of luxury and technology.",
      },
      {
        name: "Chris D.",
        rating: 4,
        comment: "Beautiful watch. Battery life could be longer.",
      },
    ],
  },
  {
    id: 5,
    name: "Stealth Black Pro",
    slug: "stealth-black-pro",
    category: "Smart Watches",
    price: 219.99,
    oldPrice: 270.0,
    rating: 5,
    stock: 6,
    badge: "Trending",
    description:
      "Dark, bold, and powerful. The Stealth Black Pro features an all-black design with military-grade durability. Built for those who demand performance in any environment.",
    features: [
      "Military-grade durability",
      "All-black design",
      "6-day battery life",
      "GPS + GLONASS",
      "Water resistant 100m",
      "Altimeter & barometer",
    ],
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Brian M.",
        rating: 5,
        comment:
          "Absolute beast of a watch. Survived a hiking trip no problem.",
      },
      {
        name: "Zoe T.",
        rating: 5,
        comment: "Love the all-black look. Very sleek.",
      },
      {
        name: "Nathan L.",
        rating: 5,
        comment: "Best outdoor watch I've ever owned.",
      },
    ],
  },
  {
    id: 6,
    name: "Urban Classic",
    slug: "urban-classic",
    category: "Smart Watches",
    price: 179.99,
    oldPrice: 220.0,
    rating: 4,
    stock: 20,
    badge: "Trending",
    description:
      "The Urban Classic is designed for the modern city dweller. Clean lines, a slim profile, and smart features make it perfect for everyday wear.",
    features: [
      "Slim profile",
      "Clean minimalist design",
      "5-day battery life",
      "Smartphone notifications",
      "Step tracking",
      "Water resistant 30m",
    ],
    images: [
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Sophie R.",
        rating: 4,
        comment: "Love the minimalist design. Very elegant.",
      },
      {
        name: "Jack F.",
        rating: 4,
        comment: "Great everyday watch. Comfortable to wear.",
      },
      {
        name: "Nina C.",
        rating: 5,
        comment: "Perfect for office and casual wear.",
      },
    ],
  },
  {
    id: 7,
    name: "Pulse Tracker X",
    slug: "pulse-tracker-x",
    category: "Fitness Bands",
    price: 69.99,
    oldPrice: 90.0,
    rating: 5,
    stock: 18,
    badge: "Trending",
    description:
      "The Pulse Tracker X is your affordable health companion. Tracks heart rate, steps, sleep, and calories with impressive accuracy. A great starter fitness band.",
    features: [
      "Continuous heart rate",
      "Step counter",
      "Sleep tracking",
      "Calorie tracking",
      "14-day battery life",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Paul N.",
        rating: 5,
        comment: "Amazing value for money. Does everything I need.",
      },
      {
        name: "Rachel S.",
        rating: 5,
        comment: "Battery life is incredible. Highly recommend.",
      },
      { name: "John D.", rating: 4, comment: "Great starter fitness band." },
    ],
  },
  {
    id: 8,
    name: "FitBand Ultra",
    slug: "fitband-ultra",
    category: "Fitness Bands",
    price: 59.99,
    oldPrice: 79.0,
    rating: 4,
    stock: 9,
    badge: "Trending",
    description:
      "Slim, smart, and affordable. The FitBand Ultra tracks your daily activity with a beautiful color display and long battery life.",
    features: [
      "Color display",
      "Activity tracking",
      "Sleep monitoring",
      "Weather updates",
      "10-day battery",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Amy G.",
        rating: 4,
        comment: "Love the color display. Very clear and bright.",
      },
      {
        name: "Steve H.",
        rating: 4,
        comment: "Good budget band. Does what it says.",
      },
      {
        name: "Laura M.",
        rating: 5,
        comment: "Best budget fitness band out there.",
      },
    ],
  },
  {
    id: 9,
    name: "CardioMax Band",
    slug: "cardiomax-band",
    category: "Fitness Bands",
    price: 79.99,
    oldPrice: 99.0,
    rating: 5,
    stock: 14,
    badge: "Trending",
    description:
      "Designed for serious cardio enthusiasts, the CardioMax Band provides advanced heart rate zones, VO2 max, and recovery tracking.",
    features: [
      "Heart rate zones",
      "VO2 max tracking",
      "Recovery score",
      "Workout detection",
      "7-day battery",
      "Water resistant 50m",
    ],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Mike T.",
        rating: 5,
        comment: "Recovery tracking has improved my training significantly.",
      },
      {
        name: "Anna B.",
        rating: 5,
        comment: "Heart rate zones are super accurate.",
      },
      { name: "Dan W.", rating: 4, comment: "Great cardio companion." },
    ],
  },
  {
    id: 10,
    name: "SlimFit Tracker",
    slug: "slimfit-tracker",
    category: "Fitness Bands",
    price: 49.99,
    oldPrice: 65.0,
    rating: 4,
    stock: 22,
    badge: "Trending",
    description:
      "The SlimFit Tracker is the thinnest band in our lineup. Ultra-lightweight and comfortable for all-day wear with essential health tracking features.",
    features: [
      "Ultra-slim design",
      "Step tracking",
      "Heart rate monitor",
      "Sleep tracking",
      "12-day battery",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Bella R.",
        rating: 4,
        comment: "So light I forget I'm wearing it!",
      },
      { name: "Oscar M.", rating: 4, comment: "Perfect for everyday use." },
      { name: "Chloe K.", rating: 5, comment: "Best slim tracker I've tried." },
    ],
  },
  {
    id: 11,
    name: "Diamond Luxury",
    slug: "diamond-luxury",
    category: "Luxury Watches",
    price: 499.99,
    oldPrice: 599.0,
    rating: 5,
    stock: 5,
    badge: "Trending",
    description:
      "The Diamond Luxury is the pinnacle of our collection. Adorned with premium materials and packed with smart features, this watch is a statement piece.",
    features: [
      "Premium materials",
      "Diamond-cut bezel",
      "NFC payments",
      "4-day battery",
      "Sapphire crystal",
      "Water resistant 50m",
    ],
    images: [
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Victoria L.",
        rating: 5,
        comment: "Absolutely stunning. Worth every penny.",
      },
      {
        name: "James R.",
        rating: 5,
        comment: "The most beautiful watch I've ever owned.",
      },
      { name: "Elena S.", rating: 5, comment: "Perfect luxury gift." },
    ],
  },
  {
    id: 12,
    name: "Gold Prestige",
    slug: "gold-prestige",
    category: "Luxury Watches",
    price: 599.99,
    oldPrice: 720.0,
    rating: 4,
    stock: 3,
    badge: "Trending",
    description:
      "The Gold Prestige combines old-world luxury with modern technology. A timeless design that never goes out of style.",
    features: [
      "18k gold plating",
      "Leather strap",
      "NFC payments",
      "3-day battery",
      "Sapphire crystal",
      "Water resistant 30m",
    ],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Henry W.",
        rating: 4,
        comment: "Exquisite craftsmanship. Truly a luxury piece.",
      },
      {
        name: "Diana C.",
        rating: 5,
        comment: "Gets compliments everywhere I wear it.",
      },
      {
        name: "George T.",
        rating: 4,
        comment: "Beautiful but battery could last longer.",
      },
    ],
  },
  {
    id: 13,
    name: "Platinum Series",
    slug: "platinum-series",
    category: "Luxury Watches",
    price: 799.99,
    oldPrice: 950.0,
    rating: 5,
    stock: 4,
    badge: "Trending",
    description:
      "The Platinum Series is our most exclusive watch. Crafted from aerospace-grade platinum with a hand-finished dial and premium smart features.",
    features: [
      "Aerospace-grade platinum",
      "Hand-finished dial",
      "NFC payments",
      "5-day battery",
      "Sapphire crystal",
      "Water resistant 50m",
    ],
    images: [
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Arthur N.",
        rating: 5,
        comment: "The ultimate luxury smartwatch. Flawless.",
      },
      {
        name: "Isabella M.",
        rating: 5,
        comment: "Worth every cent. Exceptional quality.",
      },
      {
        name: "William P.",
        rating: 5,
        comment: "The finest watch I've ever worn.",
      },
    ],
  },
  {
    id: 14,
    name: "Elite Rose Gold",
    slug: "elite-rose-gold",
    category: "Luxury Watches",
    price: 649.99,
    oldPrice: 780.0,
    rating: 5,
    stock: 6,
    badge: "Trending",
    description:
      "Feminine, elegant, and smart. The Elite Rose Gold features a rose gold case with a stunning AMOLED display and premium health tracking.",
    features: [
      "Rose gold case",
      "AMOLED display",
      "Health tracking",
      "NFC payments",
      "4-day battery",
      "Water resistant 30m",
    ],
    images: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Sophia K.",
        rating: 5,
        comment: "Most beautiful watch I've ever seen!",
      },
      {
        name: "Olivia T.",
        rating: 5,
        comment: "The rose gold finish is stunning.",
      },
      {
        name: "Charlotte B.",
        rating: 4,
        comment: "Elegant and smart. Love it!",
      },
    ],
  },
  {
    id: 15,
    name: "Kids Dino Watch",
    slug: "kids-dino-watch",
    category: "Kids Watches",
    price: 29.99,
    oldPrice: 39.0,
    rating: 5,
    stock: 25,
    badge: "Trending",
    description:
      "Fun, colorful, and durable! The Kids Dino Watch features a dinosaur theme, step counter, alarm, and stopwatch — perfect for active kids.",
    features: [
      "Dinosaur theme",
      "Step counter",
      "Alarm clock",
      "Stopwatch",
      "Durable design",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Parent A.",
        rating: 5,
        comment: "My kid absolutely loves this watch!",
      },
      {
        name: "Parent B.",
        rating: 5,
        comment: "Very durable. Survived many adventures.",
      },
      {
        name: "Parent C.",
        rating: 4,
        comment: "Great kids watch. Easy to use.",
      },
    ],
  },
  {
    id: 16,
    name: "Kids Sport Band",
    slug: "kids-sport-band",
    category: "Kids Watches",
    price: 24.99,
    oldPrice: 34.0,
    rating: 4,
    stock: 30,
    badge: "Trending",
    description:
      "Keep your active kids moving with the Kids Sport Band. Tracks steps and activity, with a fun colorful display and parental controls.",
    features: [
      "Step tracking",
      "Activity goals",
      "Colorful display",
      "Parental controls",
      "Durable strap",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Parent D.",
        rating: 4,
        comment: "Kids love competing on step counts!",
      },
      { name: "Parent E.", rating: 4, comment: "Parental controls are great." },
      { name: "Parent F.", rating: 5, comment: "Best kids activity band." },
    ],
  },
  {
    id: 17,
    name: "Kids Galaxy Watch",
    slug: "kids-galaxy-watch",
    category: "Kids Watches",
    price: 34.99,
    oldPrice: 44.0,
    rating: 5,
    stock: 20,
    badge: "Trending",
    description:
      "Take kids on a space adventure with the Kids Galaxy Watch. Features a space theme, educational games, step counter, and alarm.",
    features: [
      "Space theme",
      "Educational games",
      "Step counter",
      "Alarm clock",
      "Durable design",
      "Water resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Parent G.",
        rating: 5,
        comment: "My son thinks he's an astronaut now!",
      },
      {
        name: "Parent H.",
        rating: 5,
        comment: "Educational and fun. Love it.",
      },
      {
        name: "Parent I.",
        rating: 4,
        comment: "Great space-themed watch for kids.",
      },
    ],
  },
  {
    id: 18,
    name: "Kids Adventure",
    slug: "kids-adventure",
    category: "Kids Watches",
    price: 39.99,
    oldPrice: 49.0,
    rating: 4,
    stock: 18,
    badge: "Trending",
    description:
      "Built for the adventurous kid, the Kids Adventure watch is rugged, waterproof, and packed with fun features including a compass and flashlight.",
    features: [
      "Rugged design",
      "Built-in compass",
      "LED flashlight",
      "Step counter",
      "Waterproof",
      "Shock resistant",
    ],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    ],
    reviews: [
      {
        name: "Parent J.",
        rating: 4,
        comment: "My daughter takes this everywhere!",
      },
      {
        name: "Parent K.",
        rating: 5,
        comment: "The flashlight is a hit at sleepovers.",
      },
      {
        name: "Parent L.",
        rating: 4,
        comment: "Very rugged. Survived the garden hose!",
      },
    ],
  },
];
